### ISSUE TITLE
Add a license to the project

### ISSUE THREAD

**Issue by itaisteinherz** [benhayehudi/pronoun_highlighter#13]
Since this is an open source project, it should have some sort of license.
Currently, the [`package.json`](https://github.com/benhayehudi/pronoun_highlighter/blob/master/package.json#L13) file states that the projects is licensed under the ISC license, but there is no `license` file in the project.

I'd suggest to either:

- Add the [full ISC license](https://choosealicense.com/licenses/isc) to the project, preferably in a file named `license`.

- Choose a different license. For more info on choosing licenses, I recommend checking out [Choose a License](https://choosealicense.com).

**Comment by benhayehudi** [comment]
Thanks @itaisteinherz, you are right, we need to add a license to the project. I see no reason not to choose the ISC license, which is the default with `npm init`. Any reason you can think of why we should choose a different one?

**Comment by itaisteinherz** [comment]
I usually use the MIT license for my personal projects, but I see no real reason to prefer it instead of the ISC license (although I'm not a lawyer, and my knowledge is basically limited to googling the subject).

This excerpt from [Choose a License](https://choosealicense.com/licenses/isc) sums it up quite well:

> The ISC license is functionally equivalent to the BSD 2-Clause and MIT licenses, removing some language that is no longer necessary.

**Comment by benhayehudi** [comment]
Yes, I also usually use the MIT license, but see no reason not to just go ahead with the ISC one in this case. I'm a bit busy with work related things the rest of the week, but I'll go ahead and add the license this weekend. Thanks again @itaisteinherz!

**Comment by benhayehudi** [comment]
The license has been added: https://github.com/benhayehudi/pronoun_highlighter/commit/6afacab00eae5a9ab7395f8f9cb5432fc9e09d73. Thanks again for bringing this up and ensuring it happened.

**Comment by itaisteinherz** [comment]
I've opened #14 to make some license-related meta improvements.
