### ISSUE TITLE
Responsive styling

### ISSUE THREAD

**Issue by benhayehudi** [benhayehudi/pronoun_highlighter#3]
**Description**

The application is a very simple one page application using Flexbox to style the various elements. 

**Request**

It would be helpful to ensure that the styling is responsive for various size devices.

**Comment by vblaha** [comment]
I'd like to work on this issue. If you have any specific changes you'd like to see from CSS, let me know. Thank you. -V

**Comment by benhayehudi** [comment]
Hi @vblaha, would love the collaboration on it! Aiming for a simple style that responds well to different screen sizes. I'd like to keep the text input and the resulted highlighted text side by side, but know that might not be possible as screen size shrinks. 

Thank you!

**Comment by vblaha** [comment]
Hey! I have this working locally (committed on my branch). I wanted to show you the changes. What do you think?

Full screen:
<img width="939" alt="screen shot 2018-11-09 at 10 12 58 pm" src="https://user-images.githubusercontent.com/40890276/48296997-cbb46c00-e46c-11e8-8dbe-ba34fd6c069d.png">

Responsive: 600px
<img width="488" alt="screen shot 2018-11-09 at 10 13 12 pm" src="https://user-images.githubusercontent.com/40890276/48296998-ce16c600-e46c-11e8-8a27-742f5df7e3c9.png">

**Comment by benhayehudi** [comment]
Hi! This looks so nice. Thank you for your CSS contributions. I really like the use of CSS grid here. I've been meaning to see it in action for a while and doing so in this context makes it all so clean and simple. I'm going to go ahead and merge the PR in just a moment.

**Comment by benhayehudi** [comment]
Closing this issue now as I believe @vblaha accomplished the goals here.

**Comment by vblaha** [comment]
I’m so glad it is what you were looking for. It was fun to work on and nice to get a taste of React before delving into it in boot camp. I’d like to continue to work on the repo if you have other things you’d like to see. Thanks!
-V

**Comment by benhayehudi** [comment]
Hi @vblaha - that sounds like a great idea. Why don't you open up a new issue on building tests and begin working on them on a new branch? Thanks so much!
